version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: i18next
    versions:
    - 19.8.5
    - 19.8.7
    - 19.8.8
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 19.9.2
    - 20.0.0
    - 20.1.0
    - 20.2.1
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: ejs
    versions:
    - 3.1.5
